server.port=8081
language=english
spring.datasource.url=jdbc:postgresql://localhost:5432/words
spring.datasource.username=natalapatak
spring.datasource.password=
spring.jpa.generate-ddl=true

# ?????????? ??? ???????? ????? ??????
audio.storage.path=./audio-files
# ???????????? ?????? ???? (? ??????????)
audio.cache.max-size=100
# ????????/????????? ???????????
audio.cache.enabled=true